# Generated by Django 4.0.6 on 2022-07-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_accounting', '0002_extendeduser_alter_category_group_delete_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватарка'),
        ),
    ]
