# Generated by Django 4.0.6 on 2022-08-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_accounting', '0006_spending_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания расходов'),
        ),
    ]
